import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import NavBar from './componentes/NavBar';
import { CssBaseline } from '@mui/material';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
          <CssBaseline />
          <NavBar />
          {children}
          </ThemeProvider>
          

        </AppRouterCacheProvider>

      </body>
    </html>
  )
}
